name: Build nesDS

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    container: devkitpro/devkitarm:20241104
    name: Build with Docker using devkitARM
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Setup environment
        run: git config --global safe.directory '*'
      - name: Build & Package nesDS
        id: build
        run: |
          make
          chmod +x make_cia
          ./make_cia --srl="nesDS.nds" --id_0=$(git rev-parse --short=7 HEAD) --tikID=$(git rev-parse --short=16 HEAD)
          mkdir nesDS/
          cp nesDS.nds nesDS/
          cp nesDS.cia nesDS/
      - name: Publish build to GH Actions
        uses: actions/upload-artifact@v4
        with:
          path: nesDS
          name: build
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            nesDS/nesDS.nds
            nesDS/nesDS.cia
